# This is a basic workflow to help you get started with Actions

name: GitHub-Actions-1
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deploy_ver_${{ github.sha }}"
  

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World!
        
      - name: Print few variables
        run: |
          echo "HI, ${{ env.APPLICATION_NAME }}"
          echo "My name: ${{ env.PACKAGE_NAME }}"
          echo "SHA number: ${{ github.sha }}"
          
      - name: List current folder
        run: ls -la
        
      - name: Cloning my repo 
        uses: actions/checkout@v1
        
      - name: Repeat List current folder
        run: ls -la
        
      - name: Test package available
        run: aws
        
  my_deploy:
    runs-on: ubuntu-18.04
    needs: [my_testing]
    steps:
       - name: Run a multi-line script
         run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    
